<?php
require_once __DIR__.'/config/database.php';
$pdo=db();
function user(): ?array { return $_SESSION['user'] ?? null; }
function require_login(): array { if(!user()) redirect('page=login'); return user(); }
function role(string ...$roles): array { $u=require_login(); if(!in_array($u['role'],$roles,true)){ http_response_code(403); exit('Akses ditolak.'); } return $u; }
function q(string $sql,array $p=[]): PDOStatement { $s=db()->prepare($sql); $s->execute($p); return $s; }
function log_action(string $action): void { if(user()) q('INSERT INTO logs(user_id,action) VALUES(?,?)',[user()['id'],$action]); }

$action=$_GET['action']??$_POST['action']??''; $page=$_GET['page']??(user()?'dashboard':'login');
if($action==='logout'){ session_destroy(); session_start(); flash('success','Anda telah logout.'); redirect('page=login'); }
if($action==='login' && $_SERVER['REQUEST_METHOD']==='POST') { verify_csrf(); $s=q('SELECT u.*,r.name role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=? AND u.active=1', [strtolower(trim($_POST['email']??''))]); $u=$s->fetch(PDO::FETCH_ASSOC); if($u && password_verify($_POST['password']??'',$u['password'])){ session_regenerate_id(true); $_SESSION['user']=$u; log_action('Login'); redirect('page=dashboard'); } flash('danger','Email atau password salah.'); redirect('page=login'); }
if($action==='save' && $_SERVER['REQUEST_METHOD']==='POST') { $u=role('Admin','Guru'); verify_csrf(); $entity=$_POST['entity']??''; $id=(int)($_POST['id']??0); $map=['majors'=>['name','code'],'academic_years'=>['name','active'],'classes'=>['name','major_id','academic_year_id'],'subjects'=>['name','code','teacher_id']]; if(!isset($map[$entity])) exit('Entitas tidak valid'); if($u['role']!=='Admin' && !in_array($entity,['subjects'],true)) exit('Akses ditolak'); $fields=$map[$entity]; $values=[]; foreach($fields as $f)$values[]=trim((string)($_POST[$f]??''))?:null; if($id){ $set=implode(',',array_map(fn($f)=>"$f=?",$fields)); q("UPDATE $entity SET $set WHERE id=?",[...$values,$id]); } else { q("INSERT INTO $entity (".implode(',',$fields).") VALUES (".rtrim(str_repeat('?,',count($fields)),',').")",$values); } flash('success','Data berhasil disimpan.'); redirect('page=manage&entity='.$entity); }
if($action==='delete'){ role('Admin'); $entity=$_GET['entity']??''; $id=(int)($_GET['id']??0); if(in_array($entity,['majors','academic_years','classes','subjects','exams','questions','users'],true)&&$id){q("DELETE FROM $entity WHERE id=?",[$id]);flash('success','Data dihapus.');} redirect('page='.($entity==='users'?'users':'manage&entity='.$entity));}
if($action==='user_save' && $_SERVER['REQUEST_METHOD']==='POST'){ role('Admin');verify_csrf();$id=(int)($_POST['id']??0);$r=(int)$_POST['role_id'];$name=trim($_POST['name']);$email=strtolower(trim($_POST['email']));if($id){$pass=trim($_POST['password']??'');if($pass!==''){if(strlen($pass)<6){flash('danger','Password minimal 6 karakter.');redirect('page=users');}q('UPDATE users SET role_id=?,name=?,email=?,password=?,active=? WHERE id=?',[$r,$name,$email,password_hash($pass,PASSWORD_DEFAULT),(int)($_POST['active']??1),$id]);}else{q('UPDATE users SET role_id=?,name=?,email=?,active=? WHERE id=?',[$r,$name,$email,(int)($_POST['active']??1),$id]);}}else{$pass=$_POST['password']??'';if(strlen($pass)<6){flash('danger','Password minimal 6 karakter.');redirect('page=users');}q('INSERT INTO users(role_id,name,email,password,active) VALUES(?,?,?,?,1)',[$r,$name,$email,password_hash($pass,PASSWORD_DEFAULT)]);$uid=(int)db()->lastInsertId();if($r===2)q('INSERT INTO teachers(user_id,nip) VALUES(?,?)',[$uid,'G'.date('Y').$uid]);if($r===3)q('INSERT INTO students(user_id,nis,class_id) VALUES(?,?,?)',[$uid,'S'.date('Y').$uid,$_POST['class_id']?:null]);}flash('success','User tersimpan.');redirect('page=users');}
if($action==='question_save' && $_SERVER['REQUEST_METHOD']==='POST'){ $u=role('Admin','Guru');verify_csrf();$id=(int)($_POST['id']??0);$sid=(int)$_POST['subject_id'];$type=$_POST['type']==='essay'?'essay':'multiple';$question=trim($_POST['question']);$weight=(float)$_POST['weight'];$teacher=$u['role']==='Guru'?q('SELECT id FROM teachers WHERE user_id=?',[$u['id']])->fetchColumn():null;if($id){if($u['role']==='Guru'){if(!q('SELECT id FROM questions WHERE id=? AND teacher_id=?',[$id,$teacher])->fetch()){flash('danger','Anda tidak punya akses ke soal ini.');redirect('page=questions');}}q('UPDATE questions SET subject_id=?,type=?,question=?,weight=? WHERE id=?',[$sid,$type,$question,$weight,$id]);q('DELETE FROM choices WHERE question_id=?',[$id]);}else{q('INSERT INTO questions(subject_id,teacher_id,type,question,weight) VALUES(?,?,?,?,?)',[$sid,$teacher,$type,$question,$weight]);$id=(int)db()->lastInsertId();}if($type==='multiple'){foreach(['A','B','C','D','E'] as $l){$txt=trim($_POST['choice_'.$l]??'');if($txt!=='')q('INSERT INTO choices(question_id,label,choice_text,is_correct) VALUES(?,?,?,?)',[$id,$l,$txt,($_POST['correct']??'')===$l]);}}flash('success','Soal tersimpan.');redirect('page=questions');}
if($action==='exam_save'&&$_SERVER['REQUEST_METHOD']==='POST'){ $u=role('Admin','Guru');verify_csrf();$id=(int)($_POST['id']??0);$token=strtoupper(trim($_POST['token']??''))?:substr(strtoupper(bin2hex(random_bytes(4))),0,8);$teacher=$u['role']==='Guru'?q('SELECT id FROM teachers WHERE user_id=?',[$u['id']])->fetchColumn():($_POST['teacher_id']?:null);if($id && $u['role']==='Guru'){if(!q('SELECT id FROM exams WHERE id=? AND teacher_id=?',[$id,$teacher])->fetch()){flash('danger','Anda tidak punya akses ke ujian ini.');redirect('page=exams');}}$data=[(int)$_POST['subject_id'],$teacher,trim($_POST['title']),trim($_POST['description']),(int)$_POST['duration'],$token,(int)isset($_POST['random_questions']),(int)isset($_POST['random_choices']),(int)isset($_POST['show_score'])];if($id){q('UPDATE exams SET subject_id=?,teacher_id=?,title=?,description=?,duration=?,token=?,random_questions=?,random_choices=?,show_score=? WHERE id=?',[...$data,$id]);}else{q('INSERT INTO exams(subject_id,teacher_id,title,description,duration,token,random_questions,random_choices,show_score) VALUES(?,?,?,?,?,?,?,?,?)',$data);$id=(int)db()->lastInsertId();}q('DELETE FROM exam_questions WHERE exam_id=?',[$id]);foreach($_POST['questions']??[] as $qid)q('INSERT IGNORE INTO exam_questions(exam_id,question_id) VALUES(?,?)',[$id,(int)$qid]);if(!empty($_POST['schedule_class'])&&!empty($_POST['starts_at'])&&!empty($_POST['ends_at']))q('INSERT INTO schedules(exam_id,class_id,starts_at,ends_at) VALUES(?,?,?,?)',[$id,(int)$_POST['schedule_class'],str_replace('T',' ',$_POST['starts_at']),str_replace('T',' ',$_POST['ends_at'])]);flash('success','Ujian tersimpan. Token: '.$token);redirect('page=exams');}
if($action==='schedule_save'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=role('Admin','Guru');verify_csrf();if($u['role']==='Guru'){$tid=q('SELECT id FROM teachers WHERE user_id=?',[$u['id']])->fetchColumn();if(!q('SELECT id FROM exams WHERE id=? AND teacher_id=?',[(int)$_POST['exam_id'],$tid])->fetch()){flash('danger','Anda tidak punya akses ke ujian ini.');redirect('page=exams');}}$start=str_replace('T',' ',$_POST['starts_at']);$end=str_replace('T',' ',$_POST['ends_at']);if(strtotime($end)<=strtotime($start)){flash('danger','Waktu selesai harus setelah waktu mulai.');redirect('page=exams');}q('INSERT INTO schedules(exam_id,class_id,starts_at,ends_at) VALUES(?,?,?,?)',[(int)$_POST['exam_id'],(int)$_POST['class_id'],$start,$end]);flash('success','Jadwal ujian dibuat.');redirect('page=exams');}
if($action==='start'&&$_SERVER['REQUEST_METHOD']==='POST'){ $u=role('Siswa');verify_csrf();$token=strtoupper(trim($_POST['token']??''));$ex=q('SELECT e.* FROM exams e JOIN schedules sc ON sc.exam_id=e.id JOIN students s ON s.class_id=sc.class_id WHERE e.token=? AND s.user_id=? AND e.active=1 AND NOW() BETWEEN sc.starts_at AND sc.ends_at',[$token,$u['id']])->fetch(PDO::FETCH_ASSOC);if(!$ex){flash('danger','Token tidak valid atau jadwal ujian belum aktif.');redirect('page=student');}$st=q('SELECT id FROM students WHERE user_id=?',[$u['id']])->fetchColumn();q("INSERT IGNORE INTO exam_results(exam_id,student_id,started_at) VALUES(?,?,NOW())",[$ex['id'],$st]);$rid=q('SELECT id FROM exam_results WHERE exam_id=? AND student_id=?',[$ex['id'],$st])->fetchColumn();redirect('page=attempt&result='.$rid);}
if($action==='save_answer'&&$_SERVER['REQUEST_METHOD']==='POST'){ $u=role('Siswa');$rid=(int)$_POST['result'];$qid=(int)$_POST['question'];$answer=trim($_POST['answer']??'');$own=q('SELECT r.id FROM exam_results r JOIN students s ON s.id=r.student_id WHERE r.id=? AND s.user_id=? AND r.status="in_progress"',[$rid,$u['id']])->fetch();if(!$own){header('Content-Type: application/json');echo json_encode(['ok'=>false]);exit;}q('INSERT INTO answers(result_id,question_id,answer_text) VALUES(?,?,?) ON DUPLICATE KEY UPDATE answer_text=VALUES(answer_text)',[$rid,$qid,$answer]);header('Content-Type: application/json');echo json_encode(['ok'=>true]);exit;}
if($action==='submit'&&$_SERVER['REQUEST_METHOD']==='POST'){ $u=role('Siswa');verify_csrf();$rid=(int)$_POST['result'];$own=q('SELECT r.id FROM exam_results r JOIN students s ON s.id=r.student_id WHERE r.id=? AND s.user_id=? AND r.status="in_progress"',[$rid,$u['id']])->fetch();if(!$own){flash('danger','Ujian tidak ditemukan atau sudah dikumpulkan.');redirect('page=student');} grade_result($rid);flash('success','Ujian berhasil dikumpulkan.');redirect('page=student');}
function grade_result(int $rid):void{$r=q('SELECT * FROM exam_results WHERE id=?',[$rid])->fetch(PDO::FETCH_ASSOC);if(!$r||$r['status']!=='in_progress')return;$qs=q('SELECT q.* FROM exam_questions eq JOIN questions q ON q.id=eq.question_id WHERE eq.exam_id=?',[$r['exam_id']])->fetchAll(PDO::FETCH_ASSOC);$earned=0;$total=0;$essay=false;foreach($qs as $x){$total+=(float)$x['weight'];if($x['type']==='essay'){$essay=true;continue;}$a=q('SELECT answer_text FROM answers WHERE result_id=? AND question_id=?',[$rid,$x['id']])->fetchColumn();$correct=q('SELECT label FROM choices WHERE question_id=? AND is_correct=1',[$x['id']])->fetchColumn();$ok=$a===$correct;$earned+=$ok?(float)$x['weight']:0;q('UPDATE answers SET is_correct=?,score=? WHERE result_id=? AND question_id=?',[$ok?1:0,$ok?$x['weight']:0,$rid,$x['id']]);}$score=$total?round($earned/$total*100,2):0;q('UPDATE exam_results SET submitted_at=NOW(),status=?,score=? WHERE id=?',[$essay?'submitted':'graded',$score,$rid]);}
if($action==='export'){$u=role('Admin','Guru');$tid=$u['role']==='Guru'?q('SELECT id FROM teachers WHERE user_id=?',[$u['id']])->fetchColumn():null;$sql='SELECT u.name siswa,e.title ujian,r.score,r.status,r.started_at,r.submitted_at FROM exam_results r JOIN students s ON s.id=r.student_id JOIN users u ON u.id=s.user_id JOIN exams e ON e.id=r.exam_id';$params=[];if($tid){$sql.=' WHERE e.teacher_id=?';$params[]=$tid;}$sql.=' ORDER BY r.id DESC';$rows=q($sql,$params)->fetchAll(PDO::FETCH_ASSOC);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=laporan-nilai.csv');$o=fopen('php://output','w');fputcsv($o,['Siswa','Ujian','Nilai','Status','Mulai','Selesai']);foreach($rows as $x)fputcsv($o,$x);exit;}
if($action==='toggle_active'&&$_SERVER['REQUEST_METHOD']==='POST'){ role('Admin');verify_csrf();$entity=$_POST['entity']??'';$id=(int)($_POST['id']??0);if(in_array($entity,['users','exams'],true)&&$id){q("UPDATE $entity SET active=1-active WHERE id=?",[$id]);flash('success','Status diperbarui.');}redirect('page='.($entity==='users'?'users':'exams'));}
require __DIR__.'/views/layout.php';
